### ISSUE TITLE
Umlauts break event length

### ISSUE THREAD

**Issue by p000010u** [teragrep/rlp_01#47]
When running RelpBatchTest I changed the line:
`private static final String message = "syslog message";`
to test with even one umlaut:
`private static final String message = "syslog messäge";`

then ran the tests and it fails with:

com.teragrep.rlp_01.RelpBatchTest.testRetryAllFailed
`Worker queue count did not match ==> expected: <2> but was: <7>`

com.teragrep.rlp_01.RelpBatchTest.testInsert
`Did not receive expected value from getRequest ==> expected: <0 syslog 14 syslog messäge> but was: <0 syslog 15 syslog messäge>`

**Comment by StrongestNumber9** [comment]
> com.teragrep.rlp_01.RelpBatchTest.testRetryAllFailed
> `Worker queue count did not match ==> expected: <2> but was: <7>

This is because of #12 and being fixed, the strlen size is valid though

**Comment by StrongestNumber9** [comment]
As far as I know the internals are working correctly, it is just that the test uses `message.length()` and not `message.getBytes().length`
